### ISSUE TITLE
nested parts in state cause issue

### ISSUE THREAD

**Issue by zspecza** [declandewet/system#9]
``` stylus
+s-component('category-scorecard')
  +s-has('category-list')
    width: 100%
    +s-has('category')
      padding: 0.5em
      transition: background .5s ease-in
      +s-is('hovered')
        background: #ccc
        cursor: pointer
        transition: background .5s ease-out
        +s-has('icon')
          animation: entice 500ms linear infinite
```

processes to

``` css
.category-scorecard--category-list--category:hover .category-scorecard--icon {
  -webkit-animation: entice 500ms linear infinite;
  animation: entice 500ms linear infinite;
}
```
